# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitcache-deployment
  namespace: gitcache
  labels:
    app: gitcache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitcache
  template:
    metadata:
      labels:
        app: gitcache
    spec:
      securityContext:
         runAsNonRoot : true
      containers:
      - name: gitcache
        env:
        - name: BLOB_URL
          value: "gs://ossf-scorecards-cache"
        - name: TEMP_DIR 
          value: "/data/gitcache"
        image: ko://github.com/ossf/scorecard/gitcache
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: gitcache-storage
              mountPath: /data/gitcache
        securityContext:
          allowPrivilegeEscalation: false 
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: gitcache-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitcache
  namespace: gitcache
spec:
  selector:
    app: gitcache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
